[package]
name = "rust-dlc"
version = "0.1.0"
authors = ["Crypto Garage"]
edition = "2018"

[dependencies]
bitcoin = "0.21"
#secp256k1 = "0.15"
# TODO - use secp256k1-zkp fork with schnorr sigs and additonal DLC functions
# currently secp256k1 forks version 0.13 which causes compatibility problems
# with the version of secp256k1 used by rust-lightning (0.15)
secp256k1-zkp = { git = "https://github.com/yancyribbens/rust-secp256k1-zkp", branch = "feature/add-schnorr-pubkey" }
# lightning = { git = "https://github.com/rust-bitcoin/rust-lightning" }
