[package]
authors = ["Crypto Garage"]
name = "dlc"
version = "0.0.1"

[dependencies]
bitcoin = {version = "0.27"}
secp256k1-sys = {version = "0.4.0"}
secp256k1-zkp = {version = "0.4.0", features = ["bitcoin_hashes", "rand-std"], git = "https://github.com/p2pderivatives/rust-secp256k1-zkp", branch = "rust-dlc-version"}
serde = {version = "1.0", default-features = false, optional = true}

[features]
use-serde = ["serde", "bitcoin/use-serde", "secp256k1-zkp/use-serde"]

[dev-dependencies]
bitcoin = {version = "0.27", features = ["use-serde"]}
bitcoin-test-utils = {path = "../bitcoin-test-utils"}
bitcoincore-rpc = {version = "0.13.0", git = "https://github.com/p2pderivatives/rust-bitcoincore-rpc", branch = "dlc-version"}
bitcoincore-rpc-json = {version = "0.13.0", git = "https://github.com/p2pderivatives/rust-bitcoincore-rpc", branch = "dlc-version"}
dlc-trie = {path = "../dlc-trie"}
secp256k1-zkp = {version = "0.4.0", features = ["bitcoin_hashes", "rand", "rand-std", "serde"], git = "https://github.com/p2pderivatives/rust-secp256k1-zkp", branch = "rust-dlc-version"}
