[package]
authors = ["Crypto Garage"]
description = "This crate provides the representation of DLC messages and functions to enable their serialization."
homepage = "https://github.com/p2pderivatives/rust-dlc"
license-file = "../LICENSE"
name = "p2pd-oracle-client"
repository = "https://github.com/p2pderivatives/rust-dlc"
version = "0.1.0"

[dependencies]
chrono = {version = "0.4.19", features = ["serde"]}
dlc-manager = {path = "../dlc-manager"}
dlc-messages = {path = "../dlc-messages", features = ["use-serde"]}
reqwest = {version = "0.11", features = ["blocking", "json"]}
secp256k1-zkp = {version = "0.5.0"}
serde = {version = "*", features = ["derive"]}

[dev-dependencies]
mockito = "0.30.0"
