[package]
authors = ["Crypto Garage"]
name = "dlc-messages"
version = "0.0.1"

[features]
use-serde = ["serde", "bitcoin/use-serde", "secp256k1-zkp/use-serde"]

[dependencies]
bitcoin = {version = "0.27"}
dlc = {version = "0.0.1", path = "../dlc"}
lightning = {version = "0.0.100", git = "https://github.com/p2pderivatives/rust-lightning", branch = "dlc-serialization-macros"}
secp256k1-zkp = {version = "0.5.0", features = ["bitcoin_hashes", "rand", "rand-std"]}
serde = {version = "1.0", features = ["derive"], optional = true}
unicode-normalization = {version = "0.1.16"}

[dev-dependencies]
bitcoin = {version = "0.27", features = ["use-serde"]}
bitcoin-test-utils = {version = "0.0.1", path = "../bitcoin-test-utils"}
secp256k1-zkp = {version = "0.5.0", features = ["use-serde"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
