[package]
authors = ["Crypto Garage"]
edition = "2018"
name = "dlc-manager"
version = "0.0.1"

[dependencies]
async-trait = "0.1.50"
bitcoin = {version = "0.27"}
dlc = {version = "0.0.1", path = "../dlc"}
dlc-messages = {version = "0.0.1", path = "../dlc-messages"}
dlc-trie = {version = "0.0.1", path = "../dlc-trie"}
lightning = {version = "0.0.100", git = "https://github.com/p2pderivatives/rust-lightning", branch = "dlc-serialization-macros"}
log = "0.4.14"
secp256k1-zkp = {version = "0.4.0", features = ["bitcoin_hashes", "rand", "rand-std"], git = "https://github.com/p2pderivatives/rust-secp256k1-zkp", branch = "rust-dlc-version"}

[dev-dependencies]
bitcoin-rpc-provider = {version = "0.0.1", path = "../bitcoin-rpc-provider"}
bitcoin-test-utils = {version = "0.0.1", path = "../bitcoin-test-utils"}
bitcoincore-rpc = {version = "0.13.0", git = "https://github.com/p2pderivatives/rust-bitcoincore-rpc", branch = "dlc-version"}
bitcoincore-rpc-json = {version = "0.13.0", git = "https://github.com/p2pderivatives/rust-bitcoincore-rpc", branch = "dlc-version"}
env_logger = "0.8.4"
mocks = {path = "../mocks"}
