on: [push, pull_request]

name: Continuous integration

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust: stable
          - rust: beta
          - rust: nightly
          - rust: 1.29.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
      - name: code coverage
        if: matrix.rust == 'stable'
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: "0.15.0"
          args: "-- --test-threads 1"
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: tarpaulin-report.html

  integration_tests:
    name: integration-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tests:
          - close
          - refund
    steps:
      - uses: actions/checkout@v2
      - name: Start bitcoin node
        run: ./scripts/start_node.sh
      - name: Run test
        run: cargo test -- --ignored integration_tests_${{ matrix.tests }}
      - name: Stop bitcoin node
        run: ./scripts/stop_node.sh
